# Generated by Django 5.0.3 on 2024-04-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('name', models.CharField(max_length=80, verbose_name='Ф.И.О. Клиента')),
                ('comment', models.TextField(max_length=500, verbose_name='Коментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
